apiVersion: v1
kind: Service
metadata:
  name: ringmaster-api
  namespace: ringmaster
  labels:
    app: ringmaster
    component: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  - name: websocket
    port: 8001
    targetPort: websocket
    protocol: TCP
  selector:
    app: ringmaster
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: ringmaster-scheduler
  namespace: ringmaster
  labels:
    app: ringmaster
    component: scheduler
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ringmaster
    component: scheduler
